---
title: "Introduction to the Course and Probability vs Statistics"
author: "Anthony Hung"
date: "2019-04-26"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

## Welcome!

I hope you are all excited for the course! Throughout this quarter we will covering topics in the theory and practical aspects of statistical tests and probabilistic inference. We will also have the time to engage in excercises to apply our knowledge to toy datasets. The course will close off with individual projects in which you work with data generated during your summer rotations using your newfound skills.

## Goals

* Review foundations of theoretical and applied understanding of probability and statistics

* Establish working knowledge of how to use R

* Instill a deeper understanding of statistical tests specific to research area

* Connect students with resources to seek out statistical advising in the future

* Carry out a data analysis project using real data


## Probability vs Statistics

While the title of this course only mentions statistics, in reality knowledge of probability and statitics go hand-in-hand. Both probability and statistics deal with analyzing the relative frequency of events that are the result of random processes.

*From Steven Skiena's "Calculated Bets" book:*

>__Probability__ deals with predicting the likelihood of future events, while __statistics__ involves the analysis of the frequency of past events.

>__Probability theory__ enables us to find the consequences of a given ideal world, while __statistical theory__ enables us to to measure the extent to which our world is ideal.

We will explore more of both of these fields throughout the course.

## Note

Note that we will be able to explore many different topic areas in this course. However, given the limited amount of time we have to spend together, we will not be able to delve very deeply into most topics to the level where you would be able to base your entire thesis work off of what you learn here. We hope to familiarize you with common statistical tools and methods and encourage you to take courses that are dedicated to exploring these topics in more depth should you require them for your thesis project.

## Bibliography

* https://www3.cs.stonybrook.edu/~skiena/jaialai/excerpts/node12.html
