---
title: "syllabus"
date: "2019-05-22"
output: workflowr::wflow_html
---

# ISTP Summer Journal Club: Statistical Theory & Methods

## Overview

A thorough understanding of statistics is essential for both experimental design and data analysis in biomedical research. Too often, time and resources are wasted due to a poor understanding of sample size and power calculations, and the reliability of scientific reports has repeatedly been scrutinized in recent years due to questionable, if not fraudulent, application of statistical tests.

In an era of increasingly accessible computational tools, big data, and an emphasis on open-access databases, the need for rigorous training in statistical methods has become more important than ever. As a requirement for admission into Pritzker, all MSTP students must have taken a statistics or biomathematics course in college. Many of us agree that further training in statistics would be a valuable resource and would help us feel more confident about the work we are doing.

Building off of a basic, college-level understanding of statistics, this course aims to have students review and teach essential statistical theory and methods. This will then allow students to use their statistical toolbox for a project that suits their particular research interests and goals.

## Objectives

_Statistical Theory_

Students will build a foundation of theoretical and applied understanding of probability and statistics. This will provide a deeper understanding of statistical tests specific to particular research areas. By the end of the course, students should have working knowledge of key concepts, including, but not limited to probability distributions, hypothesis testing, Bayesian inference, Markov models, multiple testing corrections. See the course schedule for topics covered in the course. Students should be able to apply these concepts to perform data analysis using their own data, or explain how statistical tests are used in the scientific literature.

_Statistical Methods_

This course also requires students to build computational skills in order to perform data analysis. For this course, the programming language R will be taught. Students, regardless of previous experience, will be expected to learn the fundamentals of how to use R and RStudio. Accompanying this will be a basic exposure the Unix terminal shell and Git/Github. By the end of this course, students should be familiar with the following in R: installation, variable assignment, variable types, operators and functions, data structures, reading and writing data, conditional branching, looping, loading and installing packages, writing functions, and, of course, basic statistical testing and plotting.
These concepts will be taught again for the Basic Computing in R track at the BSD QBio5 MBL boot camp. Students are expected by then to be proficient enough in R to choose the Advanced Computing in R track instead.


## Learning Objectives

* Establish a groundwork in theoretical and applied understanding of probability and distributions

* Introduce the theoretical basis behind commonly used statistical tests and assumptions inherent to each test

* Obtain a working knowledge of how to use R to streamline robust and reproducible statistical analyses

* Learn how to integrate statistical thinking into experimental work throughout the scientific process from study design to data analysis

* Connect students with resources to seek out statistical advising in the future

* Perform a data analysis project using real data

## Final Project

Following the 4-5 weeks of lectures, each student/group will be expected to prepare a 10-minute presentation to be delivered on the 10th week of classes. 

A rubric for the presentation can be found [here](https://drive.google.com/open?id=1FPfHFjK83qjQQmMX4uLujx9von8jRZlB).

## Grading

The grades for this course are based on the following criteria:

_Participation (30%):_

Students are expected to attend all sessions listed in the course schedule. In cases of expected scheduling conflicts, please notify the instructors at least 24 hours in advance for an excused absence.

_Homework (30%):_

Quizzes after each lecture will be given in order to assess understanding after each lecture. Each is quiz is due by the time the next lecture begins (except for the last lecture; the quiz will be due 48 hours after lecture ends). Because these quizzes are meant to help students review and reinforce concepts, they will be graded based on completion and effort.
Tutorials and other resources will be given for students to learn R. These tutorials must be completed by the end of the course. Grading will depend on timely submission of an R script that contains code used for the tutorial.

_Final Project (40%):_

Grading for the final project will be based on completion, effort, and a demonstrated understanding of statistical concepts. Students will need to submit all scripts/code, slides, papers, and/or other materials used in their final project before the day of their presentation.

## Outline of Course

Week 1: Course Introduction; the Central Limit Theorem; Intro to R; Probability and distributions 
Week 2: Bayesian inference; Naive Bayes classifier; Review of basic statistical tests

Week 3: Review of basic statistical tests continued; Regression

Week 4: Data visualization; Resampling methods; Power analysis

Weeks 6-9: Breakouts within specific programs (No formal lecture. Independent time to complete final project.)

* Work with PIs or senior grad students in same research area

* Handle real data and work hands-on with analysis tools used by people in the field

* Prepare a presentation with results of statistical analyses

* Week 7: Final project proposed to instructors

Week 10 : Project presentations

## Academic Integrity

In this course, students are expected to produce original work. This means that all sources used in written work (including articles, books, chalk posts) should be properly cited. The University policy on academic honesty is central to the ideals that undergird this course. Students are expected to be independently familiar with the policy and to recognize that their work in the course is to be their own original work that truthfully represents the time and effort applied. Violations of the policy are taken seriously and will be handled in a manner that fully represents the extent of the policy and that befits the seriousness of its violation.

## Disability Accommodations

If you have specific physical, psychiatric or learning disabilities and require accommodations, please let the instructors know early in the course so that your learning needs may be appropriately met. You will also need to meet with the Office of Student Disability Services located at 5501 S Ellis Avenue.

## Final Note

As course instructors, we understand that everyone has had different experiences and backgrounds in statistics. Thus, we are aware that a concept taught in lecture may be review for one and new to another. What you get out of this course ultimately depends on how much effort you put in. We know that laboratory rotations will take most of your time, but we hope that you challenge yourself to learn something new in this course. We want this course to be helpful for you, so please give us feedback throughout the course.

The reason we also encourage you to learn basic computing in R is that you will encounter lessons in R again at BSD QBio. We do not want your learning in this class the the boot camp to be redundant, and therefore hope this course becomes a stepping stone for you to learn more advanced computing at the boot camp. We hope this sounds fair, and do not expect the tutorials to take too long.

Finally, we hope that the final project on a topic of your choice will be something that is relevant to your graduate studies and something you are excited about. Please feel free to email us for office hours if you need any help selecting a topic for your final project. Overall, we are excited for the opportunity to work with and get to better know you all. We hope you are as well!

~Anthony and Allen


## Acknowledgements

Thank you very much to Frank Wen and Katie Lee, who started the course and gave helpful advice on course material and structure.
